# Generated by Django 5.1.1 on 2024-09-15 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_forum_ids', to='forum.forummodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
